# Generated by Django 4.2.26 on 2025-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
